// eslint-disable-next-line import/no-extraneous-dependencies
const swaggerAutogen = require('swagger-autogen')();

const outputFile = './swagger_output.json';
const routesFiles = ['./routes/website.js', './routes/backup.js'];

const doc = {
  info: {
    version: '1.0.0',
    title: 'My API',
    description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:3000',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'Website',
      description: 'Endpoints',
    },
    {
      name: 'Backup',
      description: 'Endpoints',
    },
  ],
  definitions: {
    Website: {
      title: 'fdghjk',
      description: 'fghj',
      domain: ['hkl'],
      typeOfDomain: 'school',
      cpu: 'intel core i7',
      memory: 673,
      status: 10,
    },
    addWebsite: {
      $title: 'fdghjk,',
      $description: 'fghj',
      $domain: ['hkl'],
      $typeOfDomain: 'school',
      $cpu: 'intel core i7',
      $memory: 673,
      $status: 10,
    },
    Backup: {
      siteId: 1,
      description: 'ddd',
    },
    addBackup: {
      $siteId: 1,
      $descriprtion: 'fghj',
    },
  },
};

// eslint-disable-next-line global-require
swaggerAutogen(outputFile, routesFiles, doc).then(() => { require('./app'); });
